### ISSUE TITLE
Travis claims not to know about this project

### ISSUE THREAD

**Issue by ms-ati** [laserlemon/rspec-wait#19]
When I click on the Build Status badge, I reach a page at Travis CI indicating that it is not configured for this project.

Is this project dead?

If alive, does it work with RSpec 3.6?

Thanks!

**Comment by laserlemon** [comment]
Strange, thanks for letting me know! I see the Travis build page just fine, even when signed out. You should be able to see it here: https://travis-ci.org/laserlemon/rspec-wait

This project is not dead. It is very much alive. I just hadn't updated the dependencies in a little bit. I have now and the Travis build is currently running. All signs point to RSpec::Wait still working as expected on all versions of RSpec 3. I've also set up Travis to run on a weekly basis against the very latest version of RSpec so that as soon as the day comes (give or take a week) that a new RSpec release breaks RSpec::Wait, I'll know about it and can work on a fix.

Thank you for posting your issue and I hope you find RSpec::Wait useful!
